# Generated by Django 3.1.4 on 2021-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDetect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTime', models.CharField(max_length=40)),
                ('userEar', models.FloatField(max_length=40)),
                ('userStatus', models.IntegerField()),
                ('userCreateTime', models.CharField(max_length=40)),
                ('userNickName', models.CharField(default='unknown', max_length=40)),
                ('userDetectClass', models.CharField(default='unknown', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FacePose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTime', models.CharField(max_length=40)),
                ('userPitch', models.FloatField(max_length=40)),
                ('userStatus', models.IntegerField(max_length=20)),
                ('userCreateTime', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=20)),
                ('userAdderss', models.CharField(max_length=100)),
                ('userImg', models.CharField(max_length=150)),
                ('userRank', models.IntegerField()),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
    ]
