# Generated by Django 3.1.7 on 2021-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepose',
            name='userDetectClass',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='facepose',
            name='userNickName',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
