# Generated by Django 3.1.4 on 2021-01-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDetect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTime', models.CharField(max_length=20, unique=True)),
                ('userEar', models.FloatField(max_length=20)),
                ('userStatus', models.IntegerField(max_length=20)),
                ('userCreateTime', models.CharField(max_length=20)),
            ],
        ),
    ]
