# Generated by Django 3.1.4 on 2021-01-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eyedetect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyedetect',
            name='userCreateTime',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eyedetect',
            name='userEar',
            field=models.FloatField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eyedetect',
            name='userTime',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
