# Generated by Django 3.1.4 on 2021-01-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210127_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyedetect',
            name='userTime',
            field=models.CharField(max_length=40),
        ),
    ]
