# Generated by Django 3.1.7 on 2021-02-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210127_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacePose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTime', models.CharField(max_length=40)),
                ('userPitch', models.FloatField(max_length=40)),
                ('userStatus', models.IntegerField(max_length=20)),
                ('userCreateTime', models.CharField(max_length=40)),
            ],
        ),
    ]
